name: Deploy
# on: ['deployment']
# on: ['push']
on:
  push:
    branches:
      - test

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v1

      - name: 'Deploy'
        # uses: 'deliverybot/helm@v1'
        # uses: glopezep/helm@v1.7.1
        uses: elseu/sdu-helm-deploy-action@master
        # uses: ./.github/actions/sdu-helm-deploy-action-master
        with:
          release: helm-test 
          helm: helm3
          repository: 'https://jcode-hub.github.io/helm-chart'
          repository_alias: 'mychart'
          namespace: 'hello-world'
          chart: 'mychart/helm-chart-test'
          token: '${{ github.token }}'
          value-files: 'helm-chart-sources/helm-chart-test/values.yaml'
        env:
          KUBECONFIG_BASE64: '${{ secrets.KUBECONFIG }}' #| base64
